### ISSUE TITLE
[MNGSITE-20] xml mistake in docs

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-site#1056]
**[sea.bridges@gmail.com](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sea.bridges@gmail.com)** opened **[MNGSITE-20](https://issues.apache.org/jira/browse/MNGSITE-20?redirect=false)** and commented

This xml example

\<repositories>
\<repository>
\<id>my-internal-site\</id>
\<url>http://myserver/repo\</url>
\<repository>
\</repositories>

On this page,

http://maven.apache.org/guides/introduction/introduction-to-repositories.html

Is not valid   The second \<repository> should read \</repository>

As a second note. the error that maven reports  seems to be a schema validation error,

org.apache.maven.reactor.MavenExecutionException: Parse error reading POM. Reason: Unrecognised tag: 'repository' (position: START_TAG see
n ...\</url>\n     \<repository>... `@32`:18)
at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:378)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:290)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:125)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:272)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

It would be more useful if you did encounter an error, to report well formededness exceptions first.  If the error had said something like missing end tag, I would know what the problem was right away.

---
No further details from [MNGSITE-20](https://issues.apache.org/jira/browse/MNGSITE-20?redirect=false)

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Thanks for spotting this.
Fixed in SVN r554184.
